-- COMPLETE FIX for Intelligence Dashboard (Table + RLS)
-- This script creates the table if it's missing and fixes permissions.

-- 1. Ensure Table Exists
CREATE TABLE IF NOT EXISTS public.user_intelligence_briefings (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    related_tickers TEXT,
    source_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Fix RLS policies for user_intelligence_briefings
-- Allow client-side inserts and reads
ALTER TABLE public.user_intelligence_briefings ENABLE ROW LEVEL SECURITY;

-- Drop existing restrictive policies to prevent conflicts
DROP POLICY IF EXISTS "Allow authenticated users to read briefings" ON public.user_intelligence_briefings;
DROP POLICY IF EXISTS "Allow service role to insert briefings" ON public.user_intelligence_briefings;
DROP POLICY IF EXISTS "Allow everyone to read briefings" ON public.user_intelligence_briefings;
DROP POLICY IF EXISTS "Allow everyone to insert briefings" ON public.user_intelligence_briefings;
DROP POLICY IF EXISTS "Allow everyone to update briefings" ON public.user_intelligence_briefings;
DROP POLICY IF EXISTS "Allow everyone to delete briefings" ON public.user_intelligence_briefings;

CREATE POLICY "Allow everyone to read briefings"
ON public.user_intelligence_briefings FOR SELECT
TO authenticated, anon, service_role USING (true);

CREATE POLICY "Allow everyone to insert briefings"
ON public.user_intelligence_briefings FOR INSERT
TO authenticated, anon, service_role WITH CHECK (true);

CREATE POLICY "Allow everyone to update briefings"
ON public.user_intelligence_briefings FOR UPDATE
TO authenticated, anon, service_role USING (true);

-- 3. FIX: telegram_messages (Ensure table exists just in case, though likely does)
CREATE TABLE IF NOT EXISTS public.telegram_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel TEXT,
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.telegram_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow everyone to read telegram messages" ON public.telegram_messages;
DROP POLICY IF EXISTS "Allow everyone to insert telegram messages" ON public.telegram_messages;

CREATE POLICY "Allow everyone to read telegram messages"
ON public.telegram_messages FOR SELECT
TO authenticated, anon, service_role USING (true);

CREATE POLICY "Allow everyone to insert telegram messages"
ON public.telegram_messages FOR INSERT
TO authenticated, anon, service_role WITH CHECK (true);

-- 4. FIX: ai_thought_logs
CREATE TABLE IF NOT EXISTS public.ai_thought_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT,
    ticker TEXT,
    message TEXT,
    confidence NUMERIC,
    strategy TEXT,
    details JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE public.ai_thought_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow everyone to read thought logs" ON public.ai_thought_logs;

CREATE POLICY "Allow everyone to read thought logs"
ON public.ai_thought_logs FOR SELECT
TO authenticated, anon, service_role USING (true);
