CREATE TABLE IF NOT EXISTS public.market_regime_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market TEXT NOT NULL,
    regime TEXT NOT NULL,
    score NUMERIC,
    confidence NUMERIC,
    factors JSONB,
    detailed_factors JSONB,
    recommended_exposure NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add index for faster querying by market and time
CREATE INDEX IF NOT EXISTS market_regime_logs_market_created_at_idx ON public.market_regime_logs (market, created_at DESC);

-- Enable RLS (optional, but good practice if exposed)
ALTER TABLE public.market_regime_logs ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read (for dashboard) and service role write
CREATE POLICY "Enable read access for all users" ON public.market_regime_logs FOR SELECT USING (true);
CREATE POLICY "Enable insert for service role only" ON public.market_regime_logs FOR INSERT WITH CHECK (true);
