-- ============================================================
-- JIKTOO AI - CRITICAL DATABASE FIX
-- Run this script in your Supabase SQL Editor to resolve 404 errors.
-- ============================================================

-- 1. Create 'market_regime_logs' table (Fixes 404 MarketRegimeService error)
CREATE TABLE IF NOT EXISTS public.market_regime_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market TEXT NOT NULL,
    regime TEXT NOT NULL,
    score NUMERIC,
    confidence NUMERIC,
    factors JSONB,
    detailed_factors JSONB,
    recommended_exposure NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for performance
CREATE INDEX IF NOT EXISTS market_regime_logs_market_created_at_idx 
ON public.market_regime_logs (market, created_at DESC);

-- RLS Policies (Open for service/dashboard)
ALTER TABLE public.market_regime_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON public.market_regime_logs;
CREATE POLICY "Enable read access for all users" ON public.market_regime_logs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for service role and auth users" ON public.market_regime_logs;
CREATE POLICY "Enable insert for service role and auth users" ON public.market_regime_logs FOR INSERT WITH CHECK (true);


-- 2. Update 'alpha_engine_playbooks' Schema (For Playbook First Architecture)
ALTER TABLE public.alpha_engine_playbooks 
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'WATCHING', -- 'WATCHING', 'BOUGHT', 'DISCARDED'
ADD COLUMN IF NOT EXISTS entry_plan JSONB, -- { "trigger_price": 1000, "condition": "MA20_TOUCH" }
ADD COLUMN IF NOT EXISTS scan_type TEXT; -- 'QUANT', 'NEWS', 'MANUAL'

-- Index for playbook queries
CREATE INDEX IF NOT EXISTS idx_playbooks_status_market 
ON public.alpha_engine_playbooks(status, market);

-- 3. Fix 'bfl_scanner_results' permission if needed (Optional but safe)
ALTER TABLE public.bfl_scanner_results ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public Read BFL" ON public.bfl_scanner_results;
CREATE POLICY "Public Read BFL" ON public.bfl_scanner_results FOR SELECT USING (true);
DROP POLICY IF EXISTS "Public Insert BFL" ON public.bfl_scanner_results;
CREATE POLICY "Public Insert BFL" ON public.bfl_scanner_results FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Public Update BFL" ON public.bfl_scanner_results;
CREATE POLICY "Public Update BFL" ON public.bfl_scanner_results FOR UPDATE USING (true);
