
-- Drop existing tables to clear conflicts (Schema Reset)
DROP TABLE IF EXISTS public.ai_trader_logs CASCADE;
DROP TABLE IF EXISTS public.ai_thought_logs CASCADE;

-- Recreate ai_trader_logs with proper Primary Key
CREATE TABLE public.ai_trader_logs (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    market TEXT DEFAULT 'KR',
    style TEXT,
    logs JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Recreate ai_thought_logs
CREATE TABLE public.ai_thought_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    ticker TEXT,
    action TEXT,
    confidence NUMERIC,
    message TEXT,
    details JSONB,
    strategy TEXT
);

-- Unlock RLS
ALTER TABLE public.ai_trader_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_thought_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for ai_trader_logs" ON public.ai_trader_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all for ai_thought_logs" ON public.ai_thought_logs FOR ALL USING (true) WITH CHECK (true);
