-- AI Trade Journals Table
-- Stores comprehensive post-trade analysis generated by the AI.
-- This serves as the 'Long-term Memory' for Jiktoo to learn from past trades.

create table if not exists public.ai_trade_journals (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Trade Details
    ticker text not null,
    stock_name text not null,
    entry_date timestamp with time zone not null,
    exit_date timestamp with time zone,
    entry_price numeric not null,
    exit_price numeric,
    pnl_percent numeric, -- Profit/Loss percentage
    pnl_amount numeric,  -- Realized Profit/Loss amount
    
    -- Context (The "Why")
    market_condition text, -- e.g., "BULL", "BEAR", "SIDEWAYS"
    strategy_used text,    -- e.g., "Eagle Eye", "Volume Spike"
    entry_reason text,     -- AI's reasoning at the time of entry
    
    -- Post-Mortem (The Learning)
    outcome_analysis text, -- AI's analysis of why the trade succeeded or failed
    lessons_learned text,  -- Key takeaways for future trades
    score numeric,         -- Self-assessment score (0-100)
    
    -- Metadata
    user_id uuid references auth.users(id)
);

-- Enable RLS
alter table public.ai_trade_journals enable row level security;

-- Policies
DROP POLICY IF EXISTS "Users can view their own journals" ON public.ai_trade_journals;
create policy "Users can view their own journals"
    on public.ai_trade_journals for select
    using (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own journals" ON public.ai_trade_journals;
create policy "Users can insert their own journals"
    on public.ai_trade_journals for insert
    with check (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own journals" ON public.ai_trade_journals;
create policy "Users can update their own journals"
    on public.ai_trade_journals for update
    using (auth.uid() = user_id);
