// services/strategy/MarketUniverse.ts

export const KOSPI_LEADERS = [
    { ticker: '005930', name: '삼성전자' },
    { ticker: '000660', name: 'SK하이닉스' },
    { ticker: '373220', name: 'LG에너지솔루션' },
    { ticker: '207940', name: '삼성바이오로직스' },
    { ticker: '005380', name: '현대차' },
    { ticker: '000270', name: '기아' },
    { ticker: '068270', name: '셀트리온' },
    { ticker: '005490', name: 'POSCO홀딩스' },
    { ticker: '035420', name: 'NAVER' },
    { ticker: '006400', name: '삼성SDI' },
    { ticker: '051910', name: 'LG화학' },
    { ticker: '105560', name: 'KB금융' },
    { ticker: '028260', name: '삼성물산' },
    { ticker: '012330', name: '현대모비스' },
    { ticker: '055550', name: '신한지주' },
    // Add more liquid stocks for better discovery chance
    { ticker: '003550', name: 'LG' },
    { ticker: '032830', name: '삼성생명' },
    { ticker: '086790', name: '하나금융지주' },
    { ticker: '035720', name: '카카오' },
    { ticker: '015760', name: '한국전력' },
    { ticker: '000810', name: '삼성화재' },
    { ticker: '017670', name: 'SK텔레콤' },
    { ticker: '323410', name: '카카오뱅크' },
    { ticker: '316140', name: '우리금융지주' },
    { ticker: '009150', name: '삼성전기' },
    { ticker: '259960', name: '크래프톤' },
    { ticker: '034020', name: '두산에너빌리티' },
    { ticker: '011200', name: 'HMM' },
    { ticker: '010130', name: '고려아연' },
    { ticker: '003490', name: '대한항공' },
    { ticker: '030200', name: 'KT' },
    { ticker: '018260', name: '삼성에스디에스' },
    { ticker: '032640', name: 'LG유플러스' },
    { ticker: '024110', name: '기업은행' },
    { ticker: '010950', name: 'S-Oil' },
    { ticker: '090430', name: '아모레퍼시픽' },
    { ticker: '036570', name: '엔씨소프트' },
    { ticker: '271560', name: '오리온' },
    { ticker: '011070', name: 'LG이노텍' },
    { ticker: '009540', name: 'HD한국조선해양' },
];

export const NASDAQ_LEADERS = [
    { ticker: 'AAPL', name: 'Apple Inc.' },
    { ticker: 'MSFT', name: 'Microsoft' },
    { ticker: 'GOOGL', name: 'Alphabet A' },
    { ticker: 'AMZN', name: 'Amazon' },
    { ticker: 'NVDA', name: 'NVIDIA' },
    { ticker: 'TSLA', name: 'Tesla' },
    { ticker: 'META', name: 'Meta Platforms' },
    { ticker: 'AMD', name: 'AMD' },
    { ticker: 'NFLX', name: 'Netflix' },
    { ticker: 'INTC', name: 'Intel' },
    { ticker: 'QCOM', name: 'Qualcomm' },
    { ticker: 'AVGO', name: 'Broadcom' },
    { ticker: 'CSCO', name: 'Cisco' },
    { ticker: 'TXN', name: 'Texas Instruments' },
    { ticker: 'ADBE', name: 'Adobe' },
    { ticker: 'CRM', name: 'Salesforce' },
    { ticker: 'ORCL', name: 'Oracle' },
    { ticker: 'AMAT', name: 'Applied Materials' },
    { ticker: 'MU', name: 'Micron' },
    { ticker: 'PYPL', name: 'PayPal' },
];

export const getMarketUniverse = (market: 'KR' | 'US') => {
    return market === 'KR' ? KOSPI_LEADERS : NASDAQ_LEADERS;
};
